name: tutor_ai
description: Tutor AI frontend
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  http: ^1.2.2
  provider: ^6.1.2
  record: ^6.1.2
  # web_socket_channel: ^2.4.0
  # just_audio: ^0.9.40
  # permission_handler: ^11.3.1
  ffi: ^2.1.0
  path_provider: ^2.1.3 
  path: ^1.9.0
  # speech_to_text: ^6.5.0 
  permission_handler: ^11.3.0
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/models/tiny.en.bin

# dependency_overrides:
#   record_linux: ^0.7.2
#   record_platform_interface: 1.3.0